### ISSUE TITLE
[MWCSelect] Width Control is Buggy

### ISSUE THREAD

**Issue by aress31** [material-components/material-components-web-components#1818]
**Describe the bug**
It appears that a bug exists when setting an arbitrary `width` to a `mwc-select` component, if `outlined`, the outline boundaries will not respect the set width and if `filled` the fill boundaries will behave the same way - not respecting the `width`.

**To Reproduce**
```js
<div class="flexbox" slot="actionItems">
              <hr />
              <!-- action icons -->
              <mwc-select outlined>
                <mwc-list-item
                  graphic="icon"
                  value="en"
                  selected
                  >English</mwc-list-item
                >
                <mwc-list-item graphic="icon" value="fr"
                  >French</mwc-list-item
                >
                <mwc-list-item graphic="icon" value="ar"
                  >Arabic</mwc-list-item
                >
              </mwc-select>
              <hr />
              <dark-mode-toggle
                appearance="toggle"
                permanent
              ></dark-mode-toggle>
            </div>
```

```css
mwc-select {
        width: 156px;
        padding: 0 6px;
        /* --mdc-list-side-padding: 8px; */
        /* inherits the styles of mwc-menu internally */
        --mdc-menu-item-height: 32px;
        /* --mdc-theme-surface: aliceblue; */
        /* inherits the styles of mwc-list internally */
        --mdc-list-vertical-padding: 0px;
        /* --mdc-list-side-padding: 30px; */
      }
.flexbox {
        display: flex;
        align-items: center;
      }
```

**Screenshots**
- `outlined` variant:
![image](https://user-images.githubusercontent.com/11601622/93249930-f3bc3700-f789-11ea-8911-2321016e1cee.png)

- `filled` variant:
![image](https://user-images.githubusercontent.com/11601622/93250017-13ebf600-f78a-11ea-8e06-dbce93a97c4a.png)
