### ISSUE TITLE
[MWC-DRAWER] Dark Mode

### ISSUE THREAD

**Issue by aress31** [material-components/material-components-web-components#1887]
**Describe the bug**
The `title` and `subtitle` slots of the `mwc-drawer` do not seem to respect dark/light modes.

**To Reproduce**
```js
<mwc-drawer hasHeader type="modal">
        <span slot="title">Foo</span>
        <span slot="subtitle"
          >Bar</span
        >
        <my-drawer></my-drawer>
--- SNIP ---
```

**Screenshots**
![image](https://user-images.githubusercontent.com/11601622/95522004-e1b56900-09c2-11eb-8e86-a6d678f6587a.png)

**Comment by e111077** [comment]
Workaround would be to style the colors of the components directly, but will work on a fix when we get to dark mode on this component

**Comment by e111077** [comment]
also please update your bug with the styles that you have included to enable this dark mode

**Comment by aress31** [comment]
dark.css:
```css
:root {
  --primary-color: hsl(
    var(--hue),
    calc(var(--saturation) - var(--darken)),
    calc(var(--lightness) - var(--darken))
  );
  --secondary-color: hsl(
    calc(var(--hue) + 180),
    calc(var(--saturation) - var(--darken)),
    calc(var(--lightness) - var(--darken))
  );

  --bg-color-1: hsl(0, 0%, 2.5%);
  --bg-color-2: hsl(0, 0%, 5%);
  --bg-color-3: hsl(0, 0%, 7.5%);

  --text-primary-color: hsla(0, 0%, 100%, 0.87);
  --text-secondary-color: hsla(0, 0%, 100%, 0.6);
  --text-primary-on-surface: hsl(
    var(--hue),
    calc(var(--saturation)),
    calc(var(--lightness))
  );
}
```

light.css:
```css
:root {
  --primary-color: hsl(
    var(--hue),
    var(--saturation),
    var(--lightness)
  );
  --secondary-color: hsl(
    calc(var(--hue) + 180),
    var(--saturation),
    var(--lightness)
  );

  --bg-color-1: hsl(0, 0%, 92.5%);
  --bg-color-2: hsl(0, 0%, 95%);
  --bg-color-3: hsl(0, 0%, 97.5%);

  --text-primary-color: hsla(0, 0%, 0%, 0.87);
  --text-secondary-color: hsla(0, 0%, 0%, 0.6);
  --text-primary-on-surface: hsl(
    var(--hue),
    calc(var(--saturation) - var(--darken)),
    calc(var(--lightness) - var(--darken))
  );
}
```

common.css:
```css
body {
  /* Material Design specific variables */
  --mdc-theme-primary: var(--primary-color);
  --mdc-theme-secondary: var(--secondary-color);
  --mdc-theme-text-primary-on-background: var(
    --text-secondary-color
  );
  --mdc-theme-surface: var(--bg-color-3);
  /* mwc-icon-button */
  /* default value: 24px */
  --mdc-icon-size: 20px;
  /* default value: 48px */
  --mdc-icon-button-size: 32px;
  background-color: var(--bg-color-3);
  color: var(--text-secondary-color);
  font-family: 'Roboto', Arial, Helvetica, sans-serif;
  margin: 0;
  /*  transition does not pierce shadow dom */
  /* smoothing mode switching transition */
  transition: color var(--duration) var(--timing),
    background-color var(--duration) var(--timing);
  /* transition: all 20s ease; */
}
```
