### ISSUE TITLE
mwc-textfield focus background is not working properly? (Material Guidelines) 

### ISSUE THREAD

**Issue by Biggisb** [material-components/material-components-web-components#2374]
I know is this not importent at all but i just saw it and fixed it inside our custom project and wannted to let you know.
There is no focus effect on the background when the the textfield is clicked.
What i saw is that in css  its 

```css
.mdc-text-field--filled.mdc-ripple-upgraded--background-focused
    .mdc-text-field__ripple::before,
  .mdc-text-field--filled:not(.mdc-ripple-upgraded):focus
    .mdc-text-field__ripple::before {
    transition-duration: 75ms; 
    opacity: 0.12;
    opacity: var(--mdc-ripple-focus-opacity, 0.12);
  }

//from mdc css?
```

and in mwc the class mdc-text-field--focused it been set by the component but there is no styles implemented for the background opacity.  

**To Reproduce**
1. Go to  https://material-components.github.io/material-components-web-components/demos/textfield/
2. Click on any textfield
3. to see real focus effect just use chrome inspector and set focused effect on .mdc-text-field element

**Expected behavior**
https://material.io/components/text-fields#usage
