### ISSUE TITLE
Ripple's color remains unchanged for mwc-button when text color changes

### ISSUE THREAD

**Issue by motss** [material-components/material-components-web-components#248]
## Reduced test case

[Demo at glitch](https://dirt-ermine.glitch.me/)

```css
html,
body {
  --mdc-theme-primary: #1a73e8;
}

mwc-button {
  color: #1a73e8;
}
```

## Screenshot

The ripple color remains purple which is the default color.

![{9867DC94-639D-4DF7-A838-93758F77F00E}](https://user-images.githubusercontent.com/10607759/54484409-17ef3d00-48a1-11e9-949c-5668679bf999.png)

## Affected browsers

It seems like only browsers with native Web Components does not affect by such issue.

- [x] Edge 18
- [x] IE 11
