### ISSUE TITLE
mwc-select: Transparent and non-clickable over sticky element

### ISSUE THREAD

**Issue by vsaona** [material-components/material-components-web-components#2574]
I think I found a bug, when the select menu is inside a ``sticky`` element appears over other element with ``position: sticky;`` style.

**Context:** In the page I was trying to make, I have a select and after it there is this purple-border div:
![closed](https://user-images.githubusercontent.com/44838784/126914924-2e3fe350-0c0b-4314-bbaf-034230e126d3.png)

**Expected behaviour:** When the div has ``display: block;``, it behaves normally:
![good](https://user-images.githubusercontent.com/44838784/126915016-d64deed0-1cfc-441a-80b4-2d0ba84aef0a.png)

**Actual behaviour: ** But when I make it ``sticky``, I cannot click the options that are over it:
![bad](https://user-images.githubusercontent.com/44838784/126914923-85d729e5-f641-4a01-973d-f3f35da5f7f1.png)

**Details**
A simplified version of the code that generates the problem is this:
```html
<div class = "first-div">
  <mwc-select outlined label="Arrow style">
    <mwc-list-item value = "arrow"   > Arrows    </mwc-list-item>
    <mwc-list-item value = "triangle"> Triangles </mwc-list-item>
    <mwc-list-item value = "tag"     > Tags      </mwc-list-item>
  </mwc-select>
</div>
<div class = "purple-border-div">
  text, text, <br> text text, text, <br> text
</div>
```
```css
.first-div {
  position: -webkit-sticky;
  position: sticky;
  left: 0;
}
.purple-border-div {
  position: -webkit-sticky;
  position: sticky;
  left: 0;
  border: solid #6200EE;
}
```
I've tested this in Firefox and Opera on Windows 10. I'm using Node.js (v14.16.1) to serve the files.
(The purple border has nothing to do with the problem)
