### ISSUE TITLE
mwc-select Theme Option (--mdc-select-ink-color) not working

### ISSUE THREAD

**Issue by syedabuthahirm** [material-components/material-components-web-components#885]
**I'm submitting a:**

- [x] bug report
- [ ] feature request

**What OS are you using?**

Windows 10

**Current behavior:**
--mdc-select-ink-color doesn't work

**Expected behavior:**
When We select a item the input value shout adopt (--mdc-select-ink-color) value color as mentioned in doc

**Related code:**

```css
mwc-select {
  --mdc-select-ink-color: red;
}
```
